[functions]
directory = "functions"

[context.production]
environment = { NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true" }

[context.dev]
environment = { NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true"  }